# Python 프로그래밍 Numpy
## Matrix (행렬 구조 및 연산)

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

## numpy array

In [5]:
import os
import numpy as np
#os.chdir('d:/')
os.getcwd()
'**'.join(os.listdir('.'))

'D:\\my\\script'

'.ipynb_checkpoints**Faker.ipynb**JPype1-0.7.0-cp37-cp37m-win_amd64.whl**JPype1-0.7.0-cp38-cp38-win_amd64.whl**K-Stratified.ipynb**konlpy_test.ipynb**main.py**mod1.py**mod2.py**October.ipynb**PDP_SHAP_visualization.ipynb**plot_label_propagation_versus_svm_iris.ipynb**Python_basic.ipynb**Python_numpy.ipynb**submission_knn.csv**submission_rbf.csv**text-preprocessing-using-python.ipynb**text_1101.ipynb**Untitled.ipynb**Untitled1.ipynb**__pycache__'

In [482]:
a = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
a.shape

b=np.array(range(12))
b
b.shape = (4,3)
b

c = np.arange(12)
c.shape = (4,3)

(4, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [462]:
d = np.arange(12).reshape(4,3)
d
d= np.reshape(d, (12,))
d
d= d.reshape(3,4)
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [466]:
e=np.linspace(0,11)
e.dtype
e

e=np.linspace(0,11,12)
e.dtype
e

dtype('float64')

array([ 0.        ,  0.2244898 ,  0.44897959,  0.67346939,  0.89795918,
        1.12244898,  1.34693878,  1.57142857,  1.79591837,  2.02040816,
        2.24489796,  2.46938776,  2.69387755,  2.91836735,  3.14285714,
        3.36734694,  3.59183673,  3.81632653,  4.04081633,  4.26530612,
        4.48979592,  4.71428571,  4.93877551,  5.16326531,  5.3877551 ,
        5.6122449 ,  5.83673469,  6.06122449,  6.28571429,  6.51020408,
        6.73469388,  6.95918367,  7.18367347,  7.40816327,  7.63265306,
        7.85714286,  8.08163265,  8.30612245,  8.53061224,  8.75510204,
        8.97959184,  9.20408163,  9.42857143,  9.65306122,  9.87755102,
       10.10204082, 10.32653061, 10.55102041, 10.7755102 , 11.        ])

dtype('float64')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [472]:
e=np.linspace(0,11,12).astype(int)
e.dtype
e.shape

e=np.linspace(0,11,12).astype(int).reshape(4,3)
e.shape
e.dtype

e=np.linspace(0,11,12).reshape(4,3).astype(int)
e.shape
e.dtype

dtype('int32')

(12,)

(4, 3)

dtype('int32')

(4, 3)

dtype('int32')

In [476]:
temp =[]
a =[]
for i in range(12):
    temp.append(i)
    if i % 3 == 2:
        a.append(temp)
        temp = []
a

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]

In [478]:
a = np.array(a)
a.shape

(4, 3)

In [481]:
b= np.array(range(12))
b
b.shape = (4,3)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [483]:
c = np.arange(12)
c
c.shape = (4,3)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [490]:
np.ones(12)
np.ones((4,3))
np.ones((4,3), dtype = int)
np.ones((4,3)).astype(int)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [493]:
np.zeros((4,3))
np.full((4,3), 5)
np.full((4,3), 5, dtype ='int')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [494]:
np.eye(4, dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

e = np.ones((4,3))
e

np.empty_like(e)
np.zeros_like(e)
np.ones_like(e)
np.full_like(e, 3)

# numpy array만들기 - 특수 array

In [9]:
np.ones(12)
np.ones((4,3))
np.ones((4,3), dtype =int)
np.ones((4,3)).astype(int)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# random

## uniform

In [40]:
(np.random.rand(10)) 
np.random.rand(4,3)

array([0.00967076, 0.5811707 , 0.9264978 , 0.40112479, 0.11561678,
       0.62258102, 0.99476333, 0.90862467, 0.80647225, 0.48871546])

array([[0.16737524, 0.44222418, 0.06582273],
       [0.17784661, 0.48315845, 0.82811294],
       [0.87871021, 0.49269233, 0.93180645],
       [0.77087629, 0.68337507, 0.88604281]])

##  uniform(0.1)

In [41]:
(np.random.random(10)) 
np.random.random(4,3)

array([0.65955664, 0.47100501, 0.78569379, 0.08272618, 0.29912692,
       0.80297631, 0.66864975, 0.91940183, 0.7609383 , 0.61505399])

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [34]:
np.random.random((4,3))

array([[0.50869315, 0.39376935, 0.94089576],
       [0.34509859, 0.24790354, 0.56392658],
       [0.92755917, 0.60163397, 0.93591232],
       [0.79066392, 0.50914994, 0.32421332]])

## normal(0,1)

In [44]:
np.random.randn(10) 
np.random.randn(4,3)
np.random.randn((4,3))

array([-0.97529171,  0.0724901 , -0.07322127,  0.20164168, -0.71869172,
       -0.59860342,  0.8850471 ,  1.65602284, -1.0431935 ,  0.07971256])

array([[-0.04666092, -0.61484899, -0.28482341],
       [-0.39680703, -0.6486366 ,  0.28187987],
       [-0.86307936, -0.43108537,  1.24691752],
       [ 0.2035376 , -1.01376872,  0.62608113]])

TypeError: 'tuple' object cannot be interpreted as an integer

In [73]:
np.random.choice(3,5)
np.random.choice(3,5, p = [0.2, 0.3, 0.5])
np.random.choice(['dog', 'cat', 'fish', 'bear'])
np.random.choice(['dog', 'cat', 'fish', 'bear'], 6)
np.random.choice(['dog', 'cat', 'fish', 'bear'], 6, p=[0.1, 0.1, 0.1, 0.7])

array([0, 2, 2, 2, 1])

array([2, 1, 2, 1, 2], dtype=int64)

'bear'

array(['fish', 'cat', 'cat', 'dog', 'dog', 'cat'], dtype='<U4')

array(['bear', 'bear', 'bear', 'bear', 'fish', 'bear'], dtype='<U4')

## random seed?

In [76]:
import random

print ("Random number with seed 30")
random.seed()
print ("first - ", random.randint(0, 100))

#will generate a same random number as previous
random.seed()
print ("Second - ", random.randint(0, 100))

#will generate a same random number as previous
random.seed()
print ("Third - ", random.randint(0, 100))

Random number with seed 30
first -  95
Second -  22
Third -  73


In [77]:
import random

print ("Random number with seed 30")
random.seed(12)
print ("first - ", random.randint(0, 100))

#will generate a same random number as previous
random.seed(12)
print ("Second - ", random.randint(0, 100))

#will generate a same random number as previous
random.seed(12)
print ("Third - ", random.randint(0, 100))

Random number with seed 30
first -  60
Second -  60
Third -  60


In [79]:
np.random.choice(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'), 6)
''.join(np.random.choice(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'), 6))

array(['7', 'E', 'R', 'L', 'V', 'Z'], dtype='<U1')

'WKQOTW'

In [85]:
ord('A'), ord('z')
ord('0'), ord('9')
chr(65)


(65, 122)

(48, 57)

'A'

In [100]:
letter_nums = list(range(ord('A'), ord('z')+1)) + list(range(ord('0'), ord('9')+1))
letters = [chr(i) for i in letter_nums]
''.join(np.random.choice(letters, 20))

'x7B0YG^9KM8e9w2Wo1qR'

In [101]:
nums = str(list(range(10)))[1:-1].split(', ')
nums
nums = [str(i) for i in range(10)]
nums

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [112]:
list(range(10))
list(range(10))[1:-1]
str(list(range(10))[1:-1])
str(list(range(10)))[1:-1].split(', ')

nums = str(list(range(10)))[1:-1].split(', ')
nums

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[1, 2, 3, 4, 5, 6, 7, 8]

'[1, 2, 3, 4, 5, 6, 7, 8]'

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

## 연산

In [130]:
a = np.arange(12).reshape(4,3)
a

b = np.array(range(12,0,-1)).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [122]:
a + b
a - b
a * b
a / b
a % b
a // b

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

array([[-12, -10,  -8],
       [ -6,  -4,  -2],
       [  0,   2,   4],
       [  6,   8,  10]])

array([[ 0, 11, 20],
       [27, 32, 35],
       [36, 35, 32],
       [27, 20, 11]])

array([[ 0.        ,  0.09090909,  0.2       ],
       [ 0.33333333,  0.5       ,  0.71428571],
       [ 1.        ,  1.4       ,  2.        ],
       [ 3.        ,  5.        , 11.        ]])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 2, 0],
       [0, 0, 0]], dtype=int32)

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 1,  1,  2],
       [ 3,  5, 11]], dtype=int32)

## 내적 (prodcut)

In [133]:
a
b = np.array(range(12,0,-1)).reshape(3,4)

c = np.zeros((a.shape[0], b.shape[1]), dtype = int)
c

for i in range(a.shape[0]) :
    for j in range(b.shape[1]) :
        for k in range(a.shape[1]) :
            c[i,j] += a[i,k] * b[k,j]
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

array([[ 16,  13,  10,   7],
       [ 88,  76,  64,  52],
       [160, 139, 118,  97],
       [232, 202, 172, 142]])

In [136]:
a.dot(b)
np.dot(a,b)
a@b

array([[ 16,  13,  10,   7],
       [ 88,  76,  64,  52],
       [160, 139, 118,  97],
       [232, 202, 172, 142]])

array([[ 16,  13,  10,   7],
       [ 88,  76,  64,  52],
       [160, 139, 118,  97],
       [232, 202, 172, 142]])

array([[ 16,  13,  10,   7],
       [ 88,  76,  64,  52],
       [160, 139, 118,  97],
       [232, 202, 172, 142]])

In [140]:
a
a + 3
a - 3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([[-3, -2, -1],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

## Numpy Indexing 

In [200]:
a = np.arange(40).reshape(4,10)
b= np.array([1,2,3,4,5,6,7,8,9,10])

a
a + b
a - b
a * b
a / b
a % b
a // b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [31, 33, 35, 37, 39, 41, 43, 45, 47, 49]])

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [19, 19, 19, 19, 19, 19, 19, 19, 19, 19],
       [29, 29, 29, 29, 29, 29, 29, 29, 29, 29]])

array([[  0,   2,   6,  12,  20,  30,  42,  56,  72,  90],
       [ 10,  22,  36,  52,  70,  90, 112, 136, 162, 190],
       [ 20,  42,  66,  92, 120, 150, 182, 216, 252, 290],
       [ 30,  62,  96, 132, 170, 210, 252, 296, 342, 390]])

array([[ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ,
         0.83333333,  0.85714286,  0.875     ,  0.88888889,  0.9       ],
       [10.        ,  5.5       ,  4.        ,  3.25      ,  2.8       ,
         2.5       ,  2.28571429,  2.125     ,  2.        ,  1.9       ],
       [20.        , 10.5       ,  7.33333333,  5.75      ,  4.8       ,
         4.16666667,  3.71428571,  3.375     ,  3.11111111,  2.9       ],
       [30.        , 15.5       , 10.66666667,  8.25      ,  6.8       ,
         5.83333333,  5.14285714,  4.625     ,  4.22222222,  3.9       ]])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 0, 1, 4, 3, 2, 1, 0, 9],
       [0, 1, 1, 3, 4, 1, 5, 3, 1, 9],
       [0, 1, 2, 1, 4, 5, 1, 5, 2, 9]], dtype=int32)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [10,  5,  4,  3,  2,  2,  2,  2,  2,  1],
       [20, 10,  7,  5,  4,  4,  3,  3,  3,  2],
       [30, 15, 10,  8,  6,  5,  5,  4,  4,  3]], dtype=int32)

In [201]:
a
a[1,2]
a[1][2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

12

12

In [202]:
a
a[:, 2]
a[1, :]
a[:, 2].shape
a[1, :].shape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

array([ 2, 12, 22, 32])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

(4,)

(10,)

In [203]:
a[1,]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [204]:
a[,1]

SyntaxError: invalid syntax (<ipython-input-204-1aba8269f861>, line 1)

In [205]:
a
a[:, :2]
a[:1, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31]])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [206]:
a
a[::2]
a[::-1]
a[:, 1:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

array([[ 1],
       [11],
       [21],
       [31]])

In [207]:
a
a[-1]
a[-2]
a[-2, 2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

22

In [212]:
a
a[1]
a[1, 1:8]
a[1, 1:8:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

array([11, 12, 13, 14, 15, 16, 17])

array([11, 13, 15, 17])

In [213]:
a[:2, [1,3,4]]

array([[ 1,  3,  4],
       [11, 13, 14]])

In [215]:
a
d=[0,2,3]
a[d, 2:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

array([[ 2,  3,  4,  5,  6,  7,  8],
       [22, 23, 24, 25, 26, 27, 28],
       [32, 33, 34, 35, 36, 37, 38]])

## slicing, list와 비교

In [217]:
b = list(a)
b

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])]

In [219]:
c = a.tolist()
c

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]

In [220]:
c[1,2]

TypeError: list indices must be integers or slices, not tuple

In [221]:
c[:,2]

TypeError: list indices must be integers or slices, not tuple

In [224]:
c
c[1][2] # 1번재 원소의 2번쨰 번호는 '11'

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]

12

In [226]:
c
c[1:3]

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]

[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]

In [228]:
c[1:3][1]

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [229]:
c[1:3][1][5]

25

In [234]:
a
a.shape
list(a)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

(4, 10)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])]

In [233]:
a.reshape(40,)
a.reshape(40,).shape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

(40,)

In [231]:
list(a.reshape(40,))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39]

# End 